### ISSUE TITLE
crash upon activating tower

### ISSUE THREAD

**Issue by SDUBZ** [Landmaster/LandCraft#10]
Forge:1.12.2-2532
landcraft: landcraft-2.2.1.0

crash:
[crash-2017-11-12_11.01.14-client.txt](https://github.com/Landmaster/LandCraft/files/1464246/crash-2017-11-12_11.01.14-client.txt)

**Comment by Landmaster** [comment]
@SDUBZ Is this a singleplayer or multiplayer world?

**Comment by SDUBZ** [comment]
we were playing on server but it crashed client

**Comment by Landmaster** [comment]
@SDUBZ Fixed in 2.2.1.1
