### ISSUE TITLE
client crash when mining landia portal

### ISSUE THREAD

**Issue by SDUBZ** [Landmaster/LandCraft#11]
Forge:1.12.2-2538
landcrfat:1.12.2-2.2.1.0

crash:
[crash-2017-11-14_08.13.36-client.txt](https://github.com/Landmaster/LandCraft/files/1468972/crash-2017-11-14_08.13.36-client.txt)

**Comment by Landmaster** [comment]
Fixed in a25a92a89dd0b72b41d38adec54798f4ffd6d830
