### ISSUE TITLE
duplication portals(1.12.2)

### ISSUE THREAD

**Issue by SDUBZ** [Landmaster/LandCraft#12]
Forge: 1.12.2-2559
landcraft: landcraft-2.2.1.1
landcore : landcore-1.5.0.0

https://cdn.discordapp.com/attachments/374564272815996929/388053460815446018/Screen_Shot_2017-12-06_at_2.45.16_PM.png

**Comment by Landmaster** [comment]
Not really an issue, mainly for the same reason that nether portals duplicate.
