### ISSUE TITLE
Wings performance issue

### ISSUE THREAD

**Issue by Sir-Will** [Landmaster/LandCraft#18]
landcraft-2.2.1.2
![](https://i.imgur.com/iX3zeni.jpg)

**Comment by Landmaster** [comment]
@Sir-Will Hmm… interesting. Is this SMP, or is this just singleplayer?

**Comment by Sir-Will** [comment]
Multiplayer with 20+ players and probably no player using the wings.

**Comment by Landmaster** [comment]
I may have figured out the issue: Unnecessary player capability packets are being sent.

**Comment by Sir-Will** [comment]
Yea, should be fine if it is done only for the players using the wings and only running `sendPlayerAbilities` when the state changes.

**Comment by Landmaster** [comment]
@Sir-Will Fixed in 2.2.1.3
