### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by vrork** [Landmaster/LandCraft#3]
https://gist.github.com/vrork/783a3ad02be8243ebbb8e542d96ccc6e

**Comment by Landmaster** [comment]
@vrork see BluSunrize/ImmersiveEngineering#2144 and BluSunrize/ImmersiveEngineering#2145 for a possible fix

**Comment by Landmaster** [comment]
@vrork I have released an update for LandCraft (1.3.0.0) that fixes the crash with Immersive Engineering.
