### ISSUE TITLE
Rf not showing in the block gui

### ISSUE THREAD

**Issue by ProsperCraft** [Landmaster/LandCraft#7]
https://i.gyazo.com/765f475ed218a66b0f580e35ec13dc55.png

I just launched this mod for the first time ever, dropped a creative techreborn solar panel next to it, oneprobe shows the power gaining then full, but the block shows no power.

**Comment by Landmaster** [comment]
@ProsperCraft I looked at your setup and found that you have a thorium generator from my mod. Quick question: Is the thorium generator running as well, or is it just the solar panel?

**Comment by ProsperCraft** [comment]
I don't know how the thorium generator works, I put thorium in it, and it just changed to 0% and stayed there, so i added the solar.

**Comment by Landmaster** [comment]
@ProsperCraft You also need to pump in water as well. Per Land Craft's description:

> Thorium Generator - Generates RF with thorium and water (1000 RF/tick; 400 ticks per thorium ingot; 10 mB/tick of water).

**Comment by Landmaster** [comment]
Any GUI issues have been fixed in recent versions.
